// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cuobetdigxenwftxtdhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1b2JldGRpZ3hlbndmdHh0ZGhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3ODMxNTMsImV4cCI6MjA1NDM1OTE1M30.AOWJlex5i2FOFyk5K2u6Lfz-5vKi9ZIjXj7CI_W12BQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);